### ISSUE TITLE
Corps not in alliance raise errors

### ISSUE THREAD

**Issue by ppfeufer** [pvyParts/allianceauth-corpstats-two#1]
```
[01/Jan/2020 10:02:56] ERROR [django.request:228] Internal Server Error: /corpstat/
Traceback (most recent call last):
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
response = get_response(request)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
response = self.process_exception_by_middleware(e, request)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
return view_func(request, *args, **kwargs)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/allianceauth/authentication/decorators.py", line 35, in _wrapped_view
return view_func(request, *args, **kwargs)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
return view_func(request, *args, **kwargs)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
return view_func(request, *args, **kwargs)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/corpstats/views.py", line 42, in check_corpstats
return view(request, corpstats, corp_id=corp_id)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/corpstats/views.py", line 108, in corpstat_view
return render(request, 'corpstat/corpstats.html', context=context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/shortcuts.py", line 36, in render
content = loader.render_to_string(template_name, context, request, using=using)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/loader.py", line 62, in render_to_string
return template.render(context, request)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/backends/django.py", line 61, in render
return self.template.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 171, in render
return self._render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
return self.nodelist.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 937, in render
bit = node.render_annotated(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
return self.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
return self.nodelist.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 937, in render
bit = node.render_annotated(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
return self.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/loader_tags.py", line 150, in render
return compiled_parent._render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 163, in _render
return self.nodelist.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 937, in render
bit = node.render_annotated(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
return self.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/defaulttags.py", line 309, in render
return nodelist.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 937, in render
bit = node.render_annotated(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
return self.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/loader_tags.py", line 62, in render
result = block.nodelist.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 937, in render
bit = node.render_annotated(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
return self.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/defaulttags.py", line 309, in render
return nodelist.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 937, in render
bit = node.render_annotated(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
return self.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/defaulttags.py", line 209, in render
nodelist.append(node.render_annotated(context))
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/base.py", line 904, in render_annotated
return self.render(context)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/template/defaulttags.py", line 443, in render
url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/urls/base.py", line 90, in reverse
return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
File "/home/tnnt_auth/auth-system/venv/auth/lib/python3.7/site-packages/django/urls/resolvers.py", line 673, in _reverse_with_prefix
raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'view_alliance' with arguments '(None,)' not found. 1 pattern(s) tried: ['corpstat/alliance/(?P<alliance_id>(\\d)+)/$']
```

**Comment by pvyParts** [comment]
Fixed in 1.0.2
